### ISSUE TITLE
Default :authenticate method for proof_actions does not exist

### ISSUE THREAD

**Issue by mattbrictson** [undercase/proof#10]
Out of the box, setting up `proof_actions` with a typical Rails+Devise app and invoking `POST /login` results in:

```
undefined method `authenticate' for #<User:0x007fde183bb458>
```

This is because, by default, Proof tries to call `User#authenticate`, which does not exist. For a better out of the box experience, either:
- Change the default `:authenticate` method to be `:valid_password?`, which does exist (`User#valid_password?` is provided by Devise); or
- Update the README to make it clear that developers must implement `User#authenticate` themselves

**Comment by undercase** [comment]
Hi Matt,

I just wanted to say thanks for bringing up all of these issues! I'm working really hard on fixing all of them, and your feedback is really helpful.

Thanks,
Thomas

**Comment by undercase** [comment]
The Devise generator by default sets the authenticate method to valid_password?
