### ISSUE TITLE
Proof does not load unless explicit require is specified

### ISSUE THREAD

**Issue by mattbrictson** [undercase/proof#8]
The README says to install proof with:

``` ruby
gem 'proof-rails'
```

However doing so results in proof not being loaded. Controllers where I try to use `require_proof` result in:

```
undefined method `require_proof'
```

If I try to manually include the method like this:

``` ruby
include ::Proof::RequireProof
```

I get:

```
uninitialized constant Proof
```

This is because the gem name, `proof-rails`, does not match the file, `proof.rb`, that needs to be loaded. To fix, I had to modify my Gemfile as follows:

``` ruby
gem "proof-rails", :require => "proof"
```

I suggest either modifying the README to fix the installation instructions, or add a `proof/rails.rb` file to the gem that loads the necessary files.

For the record, I am using Ruby 2.2.3 and Bundler 1.10.6.

**Comment by undercase** [comment]
Fixed the README. Thanks again :).
