### ISSUE TITLE
Default configuration returns Rails secret key in plain text!

### ISSUE THREAD

**Issue by mattbrictson** [undercase/proof#9]
Setting up `proof_actions` with the default configuration and then issuing `POST /login` with correct credentials, here is the JSON that is returned:

``` json
{
  "auth_token": {
    "data": {
      "user_id": 1,
      "exp": 1441661618
    },
    "expiration_date": 1441661618,
    "secret_key": "233d73b3b6f6da0c950d89384c00945ea80abb1f5835a22ba46935a9a4c976dad2437892262803d04df6377e3f3b0206277f77d94f6c504a2f7d1fd85def4a94",
    "algorithm": "HS256",
    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE0NDE2NjE2MTh9.IlloOcqairG5Fobx9sfTHbcppqiSlDKqQ3pnKHWdnHM"
  }
}
```

The Rails secret key is right there is plain text!

I suspect the problem is that Proof should be returning the token using `Proof::Token#to_s`, rather than using the `Proof::Token` object itself. The latter is being serialized to JSON, exposing its instance variables such as `secret_key`.

The workaround is to override the default return value, like this:

``` ruby
proof_actions do |user, token|
  {
    :auth_token => token.to_s
  }
end
```

**Comment by undercase** [comment]
Fixed in latest commit. Thanks for the notification, sorry it took me so long to get to it.
